### ISSUE TITLE
StackingDAO Pool TVL is wrong 

### ISSUE THREAD

**Issue by nieldeckx** [StackingDAO/stacking-tracker#60]

**Comment by nieldeckx** [comment]
StackingDAO signer key: 0x025588e24e2bf387fe8cc7bccba1aac7fe599b96724892431e992a40d06e8fe220

https://api.hiro.so/extended/v2/pox/cycles/92/signers/0x025588e24e2bf387fe8cc7bccba1aac7fe599b96724892431e992a40d06e8fe220/stackers
-> cycle 92 had 3 stackers (including SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR)

https://api.hiro.so/extended/v2/pox/cycles/93/signers/0x025588e24e2bf387fe8cc7bccba1aac7fe599b96724892431e992a40d06e8fe220/stackers
-> cycle 93 only has 2 stackers
-> But SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR is still stacking with the pool: https://explorer.hiro.so/address/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR?chain=mainnet

**Comment by philiphacks** [comment]
This should be fixed (can be closed), was wrongly stacked I believe by me
