### ISSUE TITLE
Mobile tables on token detail page

### ISSUE THREAD

**Issue by nieldeckx** [StackingDAO/stacking-tracker#75]
We currently have:
<img width="369" alt="Screenshot 2024-11-21 at 10 38 07" src="https://github.com/user-attachments/assets/eed62b67-1a76-4f9d-82d4-029adbee49c2">

Design is:
<img width="506" alt="Screenshot 2024-11-21 at 10 38 34" src="https://github.com/user-attachments/assets/3a44d631-31e1-4105-98ab-10cdb4f18bb5">

Example:
https://www.stacking-tracker.com/tokens/stackingdao

**Comment by Macxim** [comment]
I may have forgotten about this specific one. Will check.
